-- Neovim port of the Zed theme "Vim Default".
-- Source: ~/.config/zed/themes/vim_default.json
--
-- Zed's UI style keys map 1:1 onto Neovim highlight groups and its syntax
-- keys onto treesitter captures, so the port stays exact. The light variant
-- is used when 'background' is "light".
--
-- Usage: vim.cmd.colorscheme("vim_default")

local palette = require("vim_default.palette")

local M = {}

function M.load()
	local p = palette[vim.o.background == "light" and "light" or "dark"]
	local ui, syn, accents = p.ui, p.syntax, p.accents

	vim.cmd.highlight("clear")
	vim.g.colors_name = "vim_default"

	local hi = function(name, attrs)
		vim.api.nvim_set_hl(0, name, attrs)
	end
	local link = function(name, target)
		vim.api.nvim_set_hl(0, name, { link = target })
	end

	-- General UI
	hi("Normal", { fg = ui.text, bg = ui.background })
	link("NormalNC", "Normal")
	hi("NormalFloat", { fg = ui.text, bg = ui.elevated_background })
	hi("FloatBorder", { fg = ui.border, bg = ui.elevated_background })
	hi("FloatTitle", { fg = syn.title, bg = ui.elevated_background })
	hi("FloatFooter", { fg = ui.text_muted, bg = ui.elevated_background })
	hi("Cursor", { fg = ui.background, bg = ui.cursor })
	link("lCursor", "Cursor")
	link("TermCursor", "Cursor")
	link("CursorIM", "Cursor")
	hi("CursorLine", { bg = ui.active_line_background })
	hi("CursorColumn", { bg = ui.active_line_background })
	hi("ColorColumn", { bg = ui.wrap_guide })
	hi("LineNr", { fg = ui.line_number, bg = ui.gutter_background })
	link("LineNrAbove", "LineNr")
	link("LineNrBelow", "LineNr")
	hi("CursorLineNr", { fg = ui.active_line_number, bg = ui.gutter_background })
	link("CursorLineSign", "SignColumn")
	link("CursorLineFold", "FoldColumn")
	hi("SignColumn", { bg = ui.gutter_background })
	hi("FoldColumn", { fg = ui.indent_guide_active, bg = ui.gutter_background })
	hi("Folded", { fg = ui.text_muted, bg = ui.highlighted_line_background })
	hi("VertSplit", { fg = ui.border_variant })
	hi("WinSeparator", { fg = ui.border_variant })
	hi("StatusLine", { fg = ui.text, bg = ui.status_bar_background })
	hi("StatusLineNC", { fg = ui.text_muted, bg = ui.status_bar_background })
	hi("WinBar", { fg = ui.text, bg = ui.background })
	hi("WinBarNC", { fg = ui.text_muted, bg = ui.background })
	hi("TabLine", { fg = ui.text_muted, bg = ui.tab_bar_background })
	hi("TabLineSel", { fg = ui.text, bg = ui.tab_active_background })
	hi("TabLineFill", { bg = ui.tab_bar_background })
	hi("Pmenu", { fg = ui.text, bg = ui.elevated_background })
	hi("PmenuSel", { fg = ui.text, bg = ui.element_selected })
	link("PmenuKind", "Pmenu")
	link("PmenuKindSel", "PmenuSel")
	link("PmenuExtra", "Pmenu")
	link("PmenuExtraSel", "PmenuSel")
	link("PmenuMatch", "Pmenu")
	link("PmenuMatchSel", "PmenuSel")
	hi("PmenuSbar", { bg = ui.element_background })
	hi("PmenuThumb", { bg = ui.scrollbar_thumb })
	hi("Visual", { bg = ui.selection })
	link("VisualNOS", "Visual")
	hi("Search", { fg = ui.background, bg = ui.search_match })
	hi("IncSearch", { fg = ui.background, bg = ui.search_active })
	link("CurSearch", "IncSearch")
	link("Substitute", "IncSearch")
	link("QuickFixLine", "Visual")
	link("SnippetTabstop", "Visual")
	hi("MatchParen", { bg = ui.document_highlight_write })
	hi("NonText", { fg = ui.invisible })
	hi("EndOfBuffer", { fg = ui.background })
	hi("SpecialKey", { fg = ui.invisible })
	link("Whitespace", "NonText")
	hi("Conceal", { fg = ui.text_muted, bg = ui.background })
	hi("Ignore", { fg = ui.hidden })
	hi("Error", { fg = ui.error, bg = ui.error_background })
	hi("ErrorMsg", { fg = ui.error })
	hi("WarningMsg", { fg = ui.warning })
	hi("ModeMsg", { fg = ui.text, bold = true })
	hi("MoreMsg", { fg = ui.success, bold = true })
	link("Question", "MoreMsg")
	hi("Title", { fg = syn.title })
	hi("Directory", { fg = syn.selector })
	hi("WildMenu", { fg = ui.background, bg = ui.search_match })
	hi("Todo", { fg = ui.search_match, bold = true })
	link("MsgSeparator", "StatusLine")

	-- Spell
	hi("SpellBad", { sp = ui.error, undercurl = true })
	hi("SpellCap", { sp = ui.modified, undercurl = true })
	hi("SpellLocal", { sp = ui.info, undercurl = true })
	hi("SpellRare", { sp = ui.warning, undercurl = true })

	-- Diffs and version control
	hi("Added", { fg = ui.success })
	hi("Changed", { fg = ui.modified })
	hi("Removed", { fg = ui.deleted })
	hi("DiffAdd", { bg = ui.word_added_background })
	hi("DiffChange", { bg = ui.diff_change_background })
	hi("DiffDelete", { bg = ui.word_deleted_background })
	hi("DiffText", { bg = ui.modified_border })
	link("DiffTextAdd", "DiffText")
	hi("MiniDiffSignAdd", { fg = ui.success })
	hi("MiniDiffSignChange", { fg = ui.modified })
	hi("MiniDiffSignDelete", { fg = ui.deleted })

	-- Diagnostics and LSP
	hi("DiagnosticError", { fg = ui.error })
	hi("DiagnosticWarn", { fg = ui.warning })
	hi("DiagnosticInfo", { fg = ui.info })
	hi("DiagnosticHint", { fg = ui.hint })
	hi("DiagnosticOk", { fg = ui.success })
	hi("DiagnosticVirtualTextError", { fg = ui.error, bg = ui.error_background })
	hi("DiagnosticVirtualTextWarn", { fg = ui.warning, bg = ui.warning_background })
	hi("DiagnosticVirtualTextInfo", { fg = ui.info, bg = ui.info_background })
	hi("DiagnosticVirtualTextHint", { fg = ui.hint, bg = ui.hint_background })
	hi("DiagnosticVirtualTextOk", { fg = ui.success })
	link("DiagnosticFloatingError", "DiagnosticError")
	link("DiagnosticFloatingWarn", "DiagnosticWarn")
	link("DiagnosticFloatingInfo", "DiagnosticInfo")
	link("DiagnosticFloatingHint", "DiagnosticHint")
	link("DiagnosticFloatingOk", "DiagnosticOk")
	link("DiagnosticSignError", "DiagnosticError")
	link("DiagnosticSignWarn", "DiagnosticWarn")
	link("DiagnosticSignInfo", "DiagnosticInfo")
	link("DiagnosticSignHint", "DiagnosticHint")
	link("DiagnosticSignOk", "DiagnosticOk")
	hi("DiagnosticUnderlineError", { sp = ui.error, undercurl = true })
	hi("DiagnosticUnderlineWarn", { sp = ui.warning, undercurl = true })
	hi("DiagnosticUnderlineInfo", { sp = ui.info, undercurl = true })
	hi("DiagnosticUnderlineHint", { sp = ui.hint, undercurl = true })
	hi("DiagnosticUnderlineOk", { sp = ui.success, undercurl = true })
	hi("DiagnosticUnnecessary", { fg = ui.text_disabled })
	hi("DiagnosticDeprecated", { sp = ui.error, strikethrough = true })
	hi("LspReferenceText", { bg = ui.document_highlight_read })
	hi("LspReferenceRead", { bg = ui.document_highlight_read })
	hi("LspReferenceWrite", { bg = ui.document_highlight_write })
	hi("LspSignatureActiveParameter", { bg = ui.document_highlight_write })
	hi("LspInlayHint", { fg = ui.text_muted })
	hi("LspCodeLens", { fg = ui.text_disabled })

	-- Classic syntax groups (syntax keys without a direct equivalent use the
	-- Zed key they correspond to)
	hi("Comment", { fg = syn.comment })
	hi("Constant", { fg = syn.constant })
	hi("String", { fg = syn.string })
	hi("Character", { fg = syn.character })
	hi("Number", { fg = syn.number })
	hi("Boolean", { fg = syn.boolean })
	hi("Float", { fg = syn.number })
	hi("Identifier", { fg = syn.variable })
	hi("Function", { fg = syn["function"] })
	hi("Statement", { fg = syn.keyword })
	hi("Conditional", { fg = syn.keyword })
	hi("Repeat", { fg = syn.keyword })
	hi("Label", { fg = syn.label })
	hi("Operator", { fg = syn.operator })
	hi("Keyword", { fg = syn.keyword })
	hi("Exception", { fg = syn.keyword })
	hi("PreProc", { fg = syn.preproc })
	hi("Include", { fg = syn.preproc })
	hi("Define", { fg = syn.preproc })
	hi("Macro", { fg = syn.preproc })
	hi("PreCondit", { fg = syn.preproc })
	hi("StorageClass", { fg = syn.keyword })
	hi("Structure", { fg = syn.type })
	hi("Typedef", { fg = syn.type })
	hi("Type", { fg = syn.type })
	hi("Special", { fg = syn.special })
	hi("SpecialChar", { fg = syn.string_escape })
	hi("Tag", { fg = syn.tag })
	hi("Delimiter", { fg = syn.punctuation })
	hi("SpecialComment", { fg = syn.comment })
	hi("Debug", { fg = syn.special })
	hi("Underlined", { fg = syn.link_text, underline = true })

	-- Treesitter captures
	hi("@variable", { fg = syn.variable })
	hi("@variable.builtin", { fg = syn.variable_builtin })
	hi("@variable.parameter", { fg = syn.variable_parameter })
	hi("@variable.parameter.builtin", { fg = syn.variable_builtin })
	hi("@variable.member", { fg = syn.variable_member })
	hi("@constant", { fg = syn.constant })
	hi("@constant.builtin", { fg = syn.constant_builtin })
	hi("@constant.macro", { fg = syn.preproc })
	hi("@module", { fg = syn.namespace })
	hi("@module.builtin", { fg = syn.variable_builtin })
	hi("@label", { fg = syn.label })
	hi("@string", { fg = syn.string })
	hi("@string.documentation", { fg = syn.string })
	hi("@string.regexp", { fg = syn.string_regex })
	hi("@string.escape", { fg = syn.string_escape })
	hi("@string.special", { fg = syn.string_special })
	hi("@string.special.symbol", { fg = syn.string_special_symbol })
	hi("@string.special.path", { fg = syn.string_special })
	hi("@string.special.url", { fg = syn.link_uri, underline = true })
	hi("@character", { fg = syn.character })
	hi("@character.special", { fg = syn.string_escape })
	hi("@boolean", { fg = syn.boolean })
	hi("@number", { fg = syn.number })
	hi("@number.float", { fg = syn.number })
	hi("@type", { fg = syn.type })
	hi("@type.builtin", { fg = syn.type_builtin })
	hi("@type.definition", { fg = syn.type })
	hi("@attribute", { fg = syn.attribute })
	hi("@attribute.builtin", { fg = syn.decorator })
	hi("@decorator", { fg = syn.decorator })
	hi("@property", { fg = syn.property })
	hi("@function", { fg = syn["function"] })
	hi("@function.builtin", { fg = syn.function_builtin })
	hi("@function.call", { fg = syn["function"] })
	hi("@function.macro", { fg = syn.preproc })
	hi("@function.method", { fg = syn.method })
	hi("@function.method.call", { fg = syn.function_method_call })
	hi("@constructor", { fg = syn.constructor })
	hi("@operator", { fg = syn.operator })
	hi("@keyword", { fg = syn.keyword })
	hi("@keyword.conditional", { fg = syn.keyword })
	hi("@keyword.conditional.ternary", { fg = syn.keyword_operator })
	hi("@keyword.coroutine", { fg = syn.keyword })
	hi("@keyword.debug", { fg = syn.keyword })
	hi("@keyword.directive", { fg = syn.preproc })
	hi("@keyword.directive.define", { fg = syn.preproc })
	hi("@keyword.exception", { fg = syn.keyword })
	hi("@keyword.function", { fg = syn.keyword_function })
	hi("@keyword.import", { fg = syn.keyword })
	hi("@keyword.modifier", { fg = syn.keyword })
	hi("@keyword.operator", { fg = syn.keyword_operator })
	hi("@keyword.repeat", { fg = syn.keyword })
	hi("@keyword.return", { fg = syn.keyword_return })
	hi("@keyword.type", { fg = syn.keyword })
	hi("@punctuation.delimiter", { fg = syn.punctuation_delimiter })
	hi("@punctuation.bracket", { fg = syn.punctuation_bracket })
	hi("@punctuation.special", { fg = syn.punctuation_special })
	hi("@comment", { fg = syn.comment })
	hi("@comment.documentation", { fg = syn.comment_documentation })
	hi("@comment.error", { fg = ui.error, bg = ui.error_background })
	hi("@comment.warning", { fg = ui.warning, bg = ui.warning_background })
	hi("@comment.todo", { fg = ui.background, bg = ui.search_match })
	hi("@comment.note", { fg = ui.hint, bg = ui.hint_background })
	hi("@diff.plus", { fg = syn.diff_plus })
	hi("@diff.minus", { fg = syn.diff_minus })
	hi("@diff.delta", { fg = ui.modified })
	hi("@none", {})

	-- Markup
	hi("@markup.strong", { bold = true })
	hi("@markup.italic", { italic = true })
	hi("@markup.strikethrough", { strikethrough = true })
	hi("@markup.underline", { underline = true })
	hi("@markup.heading", { fg = syn.title })
	for level = 1, 6 do
		hi("@markup.heading." .. level, { fg = syn.title })
	end
	hi("@markup.link", { fg = syn.link_text })
	hi("@markup.link.label", { fg = syn.link_text })
	hi("@markup.link.url", { fg = syn.link_uri, underline = true })
	hi("@markup.raw", { fg = syn.text_literal })
	hi("@markup.raw.block", { fg = syn.text_literal })
	hi("@markup.list", { fg = syn.punctuation_list_marker })
	hi("@markup.list.checked", { fg = ui.success })
	hi("@markup.list.unchecked", { fg = ui.text_muted })
	hi("@markup.math", { fg = syn.string_special })
	hi("@markup.quote", { fg = syn.comment })

	-- Legacy text captures
	hi("@text.literal", { fg = syn.text_literal })
	hi("@text.reference", { fg = syn.link_text })
	hi("@text.title", { fg = syn.title })
	hi("@text.uri", { fg = syn.link_uri, underline = true })
	hi("@text.underline", { underline = true })
	hi("@text.todo", { fg = ui.background, bg = ui.search_match })
	hi("@text.note", { fg = ui.hint, bg = ui.hint_background })
	hi("@text.warning", { fg = ui.warning, bg = ui.warning_background })
	hi("@text.danger", { fg = ui.error, bg = ui.error_background })
	hi("@text.diff.add", { fg = syn.diff_plus })
	hi("@text.diff.delete", { fg = syn.diff_minus })
	hi("@text.diff.change", { fg = ui.modified })
	hi("@text.emphasis", { italic = true })
	hi("@text.strong", { bold = true })
	hi("@text.math", { fg = syn.string_special })

	-- LSP semantic tokens
	hi("@lsp.type.class", { fg = syn.type })
	hi("@lsp.type.comment", { fg = syn.comment })
	hi("@lsp.type.decorator", { fg = syn.decorator })
	hi("@lsp.type.enum", { fg = syn.enum })
	hi("@lsp.type.enumMember", { fg = syn.variant })
	hi("@lsp.type.event", { fg = syn.type })
	hi("@lsp.type.function", { fg = syn["function"] })
	hi("@lsp.type.interface", { fg = syn.type })
	hi("@lsp.type.keyword", { fg = syn.keyword })
	hi("@lsp.type.macro", { fg = syn.preproc })
	hi("@lsp.type.method", { fg = syn.method })
	hi("@lsp.type.modifier", { fg = syn.keyword })
	hi("@lsp.type.namespace", { fg = syn.namespace })
	hi("@lsp.type.number", { fg = syn.number })
	hi("@lsp.type.operator", { fg = syn.operator })
	hi("@lsp.type.parameter", { fg = syn.variable_parameter })
	hi("@lsp.type.property", { fg = syn.property })
	hi("@lsp.type.regexp", { fg = syn.string_regex })
	hi("@lsp.type.string", { fg = syn.string })
	hi("@lsp.type.struct", { fg = syn.type })
	hi("@lsp.type.type", { fg = syn.type })
	hi("@lsp.type.typeParameter", { fg = syn.type })
	hi("@lsp.type.variable", { fg = syn.variable })
	hi("@lsp.typemod.variable.defaultLibrary", { fg = syn.variable_builtin })

	-- Plugin integrations
	hi("IblIndent", { fg = ui.indent_guide })
	hi("IblScope", { fg = ui.indent_guide_active })
	link("IblWhitespace", "IblIndent")
	hi("MiniHipatternsFixme", { fg = ui.background, bg = ui.error })
	hi("MiniHipatternsHack", { fg = ui.background, bg = syn.preproc })
	hi("MiniHipatternsTodo", { fg = ui.background, bg = ui.info })
	hi("MiniHipatternsNote", { fg = ui.background, bg = ui.hidden })
	hi("MiniStatuslineModeNormal", { fg = accents[1], bg = ui.status_bar_background })
	hi("MiniStatuslineModeInsert", { fg = accents[6], bg = ui.status_bar_background })
	hi("MiniStatuslineModeVisual", { fg = accents[5], bg = ui.status_bar_background })
	hi("MiniStatuslineModeReplace", { fg = accents[2], bg = ui.status_bar_background })
	hi("MiniStatuslineModeCommand", { fg = accents[7], bg = ui.status_bar_background })
	hi("MiniStatuslineModeOther", { fg = ui.text_muted, bg = ui.status_bar_background })
	hi("MiniStatuslineDevinfo", { fg = ui.text, bg = ui.status_bar_background })
	hi("MiniStatuslineFilename", { fg = ui.text_muted, bg = ui.status_bar_background })
	hi("MiniStatuslineFileinfo", { fg = ui.text, bg = ui.status_bar_background })
	hi("MiniStatuslineInactive", { fg = ui.text_muted, bg = ui.status_bar_background })
end

return M
